# -*- coding: utf-8 -*-
"""Project_Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/thecodescholar/DA_Python_Jun_21/blob/main/Project_Titanic.ipynb

# Project_titanic
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# %matplotlib inline

"""## Data Operations Task

#### Q. Import the Titianic Dataset and Display the Head of the Dataset
"""



"""#### Q. Show the Statistics of dataframe"""



"""#### Q. Display last 3 columns"""



"""#### Q. Show Unique values in Embarked"""



"""## Visualization Task

#### Q. Draw histogram for Age, using Matplotlib
"""



"""#### Q. Draw countplot for Sex, using Seaborn"""



"""#### Q. Make a Pie Chart of Corona Cases by taking numbers list as [500000, 1800000, 1200000] and labels list as ["Deaths", "Total Cases", "Cured"]"""



"""### Great Job

## All the Best

# THE CODE SCHOLAR
"""